# Generated by Django 4.0.4 on 2022-12-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_alter_user_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=10)),
                ('type_of_business', models.CharField(max_length=50)),
                ('business_address', models.CharField(max_length=300)),
                ('district', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
